-- Seed data: 20 curated African recipes

INSERT INTO public.recipes (slug, title, description, region, country, difficulty, prep_minutes, cook_minutes, servings, tags, image_url, is_published) VALUES
('jollof-rice', 'Jollof Rice', 'The iconic West African one-pot rice dish cooked in a rich tomato and pepper sauce. A staple at celebrations across the region.', 'West Africa', 'Nigeria', 3, 30, 45, 6, ARRAY['rice', 'main dish', 'party food', 'one-pot'], '/placeholder.svg?height=400&width=600', true),
('egusi-soup', 'Egusi Soup', 'A thick, hearty Nigerian soup made from ground melon seeds, leafy greens, and assorted meats. Perfect with fufu or pounded yam.', 'West Africa', 'Nigeria', 3, 20, 40, 4, ARRAY['soup', 'main dish', 'traditional'], '/placeholder.svg?height=400&width=600', true),
('injera-with-doro-wat', 'Injera with Doro Wat', 'Ethiopian sourdough flatbread served with spicy chicken stew. The injera acts as both plate and utensil.', 'East Africa', 'Ethiopia', 4, 60, 120, 6, ARRAY['bread', 'main dish', 'spicy', 'traditional'], '/placeholder.svg?height=400&width=600', true),
('bobotie', 'Bobotie', 'South African spiced minced meat bake topped with a savory egg custard. A Cape Malay classic with sweet and savory notes.', 'Southern Africa', 'South Africa', 3, 25, 50, 6, ARRAY['main dish', 'baked', 'comfort food'], '/placeholder.svg?height=400&width=600', true),
('tagine-lamb', 'Lamb Tagine', 'Moroccan slow-cooked lamb with apricots, almonds, and warm spices. Named after the conical clay pot it is cooked in.', 'North Africa', 'Morocco', 3, 20, 90, 4, ARRAY['main dish', 'slow-cooked', 'aromatic'], '/placeholder.svg?height=400&width=600', true),
('suya', 'Suya', 'Nigerian street food of spiced skewered beef coated in ground peanuts and chili. Smoky, spicy, and utterly addictive.', 'West Africa', 'Nigeria', 2, 30, 15, 4, ARRAY['street food', 'grilled', 'spicy', 'snack'], '/placeholder.svg?height=400&width=600', true),
('fufu-and-light-soup', 'Fufu and Light Soup', 'Ghanaian pounded cassava and plantain served with a fragrant tomato-based soup with goat meat or fish.', 'West Africa', 'Ghana', 3, 30, 45, 4, ARRAY['main dish', 'traditional', 'soup'], '/placeholder.svg?height=400&width=600', true),
('piri-piri-chicken', 'Piri Piri Chicken', 'Mozambican-Portuguese grilled chicken marinated in fiery piri piri chili sauce. Charred, juicy, and intensely flavorful.', 'Southern Africa', 'Mozambique', 2, 240, 30, 4, ARRAY['grilled', 'spicy', 'main dish'], '/placeholder.svg?height=400&width=600', true),
('couscous-royal', 'Couscous Royal', 'North African semolina served with a medley of lamb, chicken, merguez sausage, and vegetables in aromatic broth.', 'North Africa', 'Morocco', 4, 30, 60, 8, ARRAY['main dish', 'feast', 'traditional'], '/placeholder.svg?height=400&width=600', true),
('shakshuka', 'Shakshuka', 'North African eggs poached in a spiced tomato and pepper sauce. Perfect for breakfast or any meal.', 'North Africa', 'Tunisia', 2, 10, 20, 2, ARRAY['breakfast', 'vegetarian', 'one-pan'], '/placeholder.svg?height=400&width=600', true),
('bunny-chow', 'Bunny Chow', 'Durban street food: a hollowed-out loaf of bread filled with spicy curry. Messy, delicious, and uniquely South African.', 'Southern Africa', 'South Africa', 2, 20, 45, 4, ARRAY['street food', 'curry', 'bread'], '/placeholder.svg?height=400&width=600', true),
('thieboudienne', 'Thieboudienne', 'Senegalese national dish of fish, rice, and vegetables cooked in a rich tomato sauce. The original jollof rice.', 'West Africa', 'Senegal', 4, 30, 60, 6, ARRAY['main dish', 'seafood', 'rice', 'national dish'], '/placeholder.svg?height=400&width=600', true),
('nyama-choma', 'Nyama Choma', 'East African grilled meat, typically goat or beef, seasoned simply with salt and served with ugali and kachumbari.', 'East Africa', 'Kenya', 2, 15, 45, 6, ARRAY['grilled', 'main dish', 'barbecue'], '/placeholder.svg?height=400&width=600', true),
('waakye', 'Waakye', 'Ghanaian rice and beans cooked with millet leaves for a distinctive reddish-brown color. A beloved breakfast staple.', 'West Africa', 'Ghana', 2, 15, 60, 6, ARRAY['breakfast', 'rice', 'beans', 'traditional'], '/placeholder.svg?height=400&width=600', true),
('maafe', 'Maafe (Groundnut Stew)', 'West African peanut butter stew with meat and vegetables. Rich, creamy, and deeply satisfying.', 'West Africa', 'Senegal', 3, 20, 50, 6, ARRAY['stew', 'main dish', 'peanut'], '/placeholder.svg?height=400&width=600', true),
('koshari', 'Koshari', 'Egyptian street food of rice, lentils, macaroni, and chickpeas topped with spiced tomato sauce and crispy onions.', 'North Africa', 'Egypt', 2, 20, 40, 4, ARRAY['vegetarian', 'street food', 'comfort food'], '/placeholder.svg?height=400&width=600', true),
('chakalaka', 'Chakalaka', 'South African spicy vegetable relish made with beans, tomatoes, peppers, and curry. Perfect braai side dish.', 'Southern Africa', 'South Africa', 1, 15, 25, 8, ARRAY['side dish', 'vegetarian', 'spicy', 'relish'], '/placeholder.svg?height=400&width=600', true),
('mandazi', 'Mandazi', 'East African fried dough, lightly sweetened and spiced with cardamom and coconut. Perfect with chai.', 'East Africa', 'Kenya', 2, 30, 20, 12, ARRAY['breakfast', 'snack', 'fried', 'sweet'], '/placeholder.svg?height=400&width=600', true),
('yassa-chicken', 'Yassa Chicken', 'Senegalese marinated chicken with caramelized onions and tangy lemon-mustard sauce. Bright, zesty flavors.', 'West Africa', 'Senegal', 3, 240, 45, 4, ARRAY['main dish', 'marinated', 'tangy'], '/placeholder.svg?height=400&width=600', true),
('puff-puff', 'Puff Puff', 'Nigerian deep-fried dough balls, crispy outside and fluffy inside. The ultimate party snack.', 'West Africa', 'Nigeria', 1, 60, 15, 20, ARRAY['snack', 'fried', 'sweet', 'party food'], '/placeholder.svg?height=400&width=600', true)
ON CONFLICT (slug) DO NOTHING;
